### ISSUE TITLE
not able to run this app in my local 

### ISSUE THREAD

**Issue by kamaldlk** [khankuan/react-sheet#3]
please help me

**Comment by khankuan** [comment]
How can I help?

**Comment by kamaldlk** [comment]
im not able to run application in my local i just clone ur repo and tried .

if u don't mind give me your skype Id 

my skype id : **kamaldlk**
mob no : **9944929666**

Thanks
Kamal K

**Comment by khankuan** [comment]
This repo is no longer maintained. However, I'll be helpful if you could show what error you're seeing.

**Comment by kamaldlk** [comment]
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "react-hot-loader/babel"
    at PluginManager.subnormaliseString (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/kamal/Projects/Learning/React/KF-grid/node_modules/babel-loader/index.js:71:12)
 @ multi react-sheet
webpack: Failed to compile.

**Comment by kamaldlk** [comment]
im new to react js i just start to learning i love ur table im planing to use my production please can we improve this lib   

my repo which i forked from ur branch https://github.com/kamaldlk/KF-grid

**Comment by khankuan** [comment]
You can consider upgrading the build and use [create-react-app](https://github.com/facebookincubator/create-react-app) as the example site.

**Comment by kamaldlk** [comment]
I need help , planning to implement use ur select range copy paste option can u help to implement 
https://github.com/kamaldlk/dataGrid this grid

**Comment by kamaldlk** [comment]
ru there brother

**Comment by khankuan** [comment]
I'm sorry I'm not actively developing on this library anymore.

**Comment by kamaldlk** [comment]
ok thanks @khankuan
